#! /bin/bash

#----------------------------------
# $Jiaqi Yang$
# $01/23/2018$
#----------------------------------

function part_1 
{              
    # Fill out your answer here

    sort -t ',' -k4,4 -k6,6 -k1,1 -k2,2 people.csv | tail -n9
    return                      
}                               

function part_2
{              
    # Fill out your answer here
    Arr=(a.txt b.txt c.txt d.txt e.txt)
    r=$(( $RANDOM%10 ))

    while (( r >= 5 ))
    do 
        r=$(( $RANDOM%10 ))
    done

    line=($( cat ${Arr[$r]} | wc -l ))
    let deter=$line%2

    if (( $deter == 0 ))
    then
        echo "Run"
        let middle=$line/2+1
        cat ${Arr[$r]} | head -n$middle | tail -n2
    else
        let middle=$line/2+1       
        cat ${Arr[$r]} | head -n$middle | tail -n1

    fi  
    return                     
}                              

function part_3
{
    # Fill out your answer here

    A=(ls ./src/*.c)
    echo $A

    #for ./src in *.c
     #   do  
      #      gcc -Wall -Werror $file -o "${file%.c}.o"
 #           if (    ( $? == 0 ))
  #          then
   #             echo "<$file>: sucess"
    #        else
     #           echo "<$file>: failure"
 #           fi
     #   done
    return
}

# To test your function, you can call it below like this:
#
part_3
